# Generated by Django 4.1.2 on 2022-11-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookreview_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='start_given',
            new_name='starts_given',
        ),
    ]
