# Generated by Django 4.1.2 on 2022-11-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_start_given_bookreview_starts_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='starts_given',
            new_name='stars_given',
        ),
    ]
