# Generated by Django 4.1.2 on 2022-11-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_author_bio_alter_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='personal_photo',
            field=models.ImageField(default='default_pic.jpg', upload_to=''),
        ),
    ]
